function sidebarItemStyle(active: boolean): React.CSSProperties {
  return {
    width: '100%',
    textAlign: 'left',
    borderRadius: 16,
    padding: '14px 16px',
    fontSize: 14,
    fontWeight: 800,
    cursor: 'pointer',
    border: active ? '1px solid #111827' : '1px solid #e5e7eb',
    background: active ? '#111827' : '#ffffff',
    color: active ? '#ffffff' : '#374151',
    boxShadow: active ? '0 12px 22px rgba(17,24,39,0.16)' : 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    boxSizing: 'border-box',
  };
}

function departmentFilterStyle(
  dept: 'ALL' | 'HK' | 'MT' | 'FO',
  active: boolean
): React.CSSProperties {
  const base: React.CSSProperties = {
    borderRadius: 999,
    padding: '10px 14px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    border: '1px solid #d1d5db',
    background: '#ffffff',
    color: '#374151',
    boxSizing: 'border-box',
  };

  if (!active) return base;

  if (dept === 'HK') {
    return {
      ...base,
      background: '#16a34a',
      color: '#ffffff',
      border: '1px solid #16a34a',
      boxShadow: '0 8px 18px rgba(22,163,74,0.22)',
    };
  }

  if (dept === 'MT') {
    return {
      ...base,
      background: '#2563eb',
      color: '#ffffff',
      border: '1px solid #2563eb',
      boxShadow: '0 8px 18px rgba(37,99,235,0.22)',
    };
  }

  if (dept === 'FO') {
    return {
      ...base,
      background: '#facc15',
      color: '#111827',
      border: '1px solid #facc15',
      boxShadow: '0 8px 18px rgba(250,204,21,0.28)',
    };
  }

  return {
    ...base,
    background: '#111827',
    color: '#ffffff',
    border: '1px solid #111827',
    boxShadow: '0 8px 18px rgba(17,24,39,0.18)',
  };
}

function statusFilterStyle(active: boolean): React.CSSProperties {
  return {
    border: active ? '1px solid #111827' : '1px solid #d1d5db',
    background: active ? '#111827' : '#ffffff',
    color: active ? '#ffffff' : '#374151',
    borderRadius: 999,
    padding: '10px 14px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    boxShadow: active ? '0 8px 18px rgba(17,24,39,0.18)' : 'none',
    boxSizing: 'border-box',
  };
}

function actionBtn(
  active: boolean,
  tone: 'open' | 'doing' | 'done'
): React.CSSProperties {
  const activeStyles =
    tone === 'open'
      ? { background: '#111827', color: '#fff', border: '1px solid #111827' }
      : tone === 'doing'
      ? { background: '#2563eb', color: '#fff', border: '1px solid #2563eb' }
      : { background: '#16a34a', color: '#fff', border: '1px solid #16a34a' };

  return {
    minWidth: 92,
    borderRadius: 12,
    padding: '10px 14px',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxSizing: 'border-box',
    ...(active
      ? activeStyles
      : {
          background: '#ffffff',
          color: '#374151',
          border: '1px solid #d1d5db',
        }),
  };
}

function statusBadgeStyle(status: Task['status']): React.CSSProperties {
  const map: Record<Task['status'], React.CSSProperties> = {
    OPEN: {
      background: '#f3f4f6',
      color: '#374151',
      border: '1px solid #e5e7eb',
    },
    IN_PROGRESS: {
      background: '#dbeafe',
      color: '#1d4ed8',
      border: '1px solid #bfdbfe',
    },
    DONE: {
      background: '#dcfce7',
      color: '#15803d',
      border: '1px solid #bbf7d0',
    },
  };

  return {
    borderRadius: 999,
    padding: '7px 12px',
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 0.2,
    whiteSpace: 'nowrap',
    boxSizing: 'border-box',
    ...map[status],
  };
}

function deptBadgeStyle(dept: Task['department']): React.CSSProperties {
  const map: Record<Task['department'], React.CSSProperties> = {
    HK: {
      background: '#dcfce7',
      color: '#15803d',
      border: '1px solid #bbf7d0',
    },
    MT: {
      background: '#dbeafe',
      color: '#1d4ed8',
      border: '1px solid #bfdbfe',
    },
    FO: {
      background: '#fef9c3',
      color: '#a16207',
      border: '1px solid #fde68a',
    },
  };

  return {
    borderRadius: 999,
    padding: '4px 10px',
    fontSize: 12,
    fontWeight: 800,
    boxSizing: 'border-box',
    ...map[dept],
  };
}

function summaryCardStyle(tone: 'open' | 'doing' | 'done'): React.CSSProperties {
  const map = {
    open: {
      background: 'linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)',
      border: '1px solid #e5e7eb',
    },
    doing: {
      background: 'linear-gradient(180deg, #eff6ff 0%, #dbeafe 100%)',
      border: '1px solid #bfdbfe',
    },
    done: {
      background: 'linear-gradient(180deg, #f0fdf4 0%, #dcfce7 100%)',
      border: '1px solid #bbf7d0',
    },
  };

  return {
    borderRadius: 20,
    padding: 18,
    boxShadow: '0 10px 24px rgba(15,23,42,0.06)',
    boxSizing: 'border-box',
    minWidth: 0,
    ...map[tone],
  };
}

function createDeptButtonStyle(
  dept: 'HK' | 'MT' | 'FO',
  active: boolean
): React.CSSProperties {
  return {
    ...departmentFilterStyle(dept, active),
    minWidth: 88,
    justifyContent: 'center',
  };
}

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: '#f3f6fb',
    overflowX: 'hidden',
    width: '100%',
  },
  layout: {
    display: 'flex',
    minHeight: '100vh',
    width: '100%',
    overflowX: 'hidden',
  },
  sidebar: {
    width: 280,
    minWidth: 280,
    background: '#ffffff',
    borderRight: '1px solid #e7edf5',
    padding: 18,
    boxShadow: '0 10px 30px rgba(15,23,42,0.05)',
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
    boxSizing: 'border-box',
    overflowX: 'hidden',
  },
  sidebarTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  sidebarBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    minWidth: 0,
    flex: 1,
  },
  sidebarLogoWrap: {
    width: 50,
    height: 50,
    borderRadius: 16,
    background: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #ede9e3',
    boxShadow: '0 8px 18px rgba(15,23,42,0.06)',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  sidebarBrandText: {
    minWidth: 0,
    flex: 1,
  },
  sidebarHotel: {
    fontSize: 15,
    fontWeight: 800,
    color: '#111827',
    lineHeight: 1.2,
    wordBreak: 'break-word',
  },
  sidebarHotelSub: {
    marginTop: 4,
    fontSize: 12,
    color: '#6b7280',
    fontWeight: 700,
  },
  sidebarCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    border: '1px solid #e5e7eb',
    background: '#ffffff',
    color: '#111827',
    fontSize: 22,
    lineHeight: 1,
    cursor: 'pointer',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  sidebarSectionTitle: {
    fontSize: 11,
    fontWeight: 800,
    color: '#94a3b8',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  sidebarMenu: {
    display: 'grid',
    gap: 10,
  },
  sidebarDivider: {
    height: 1,
    background: '#edf2f7',
    margin: '4px 0',
  },
  userPanel: {
    display: 'grid',
    gap: 10,
  },
  loginSidebarBtn: {
    borderRadius: 14,
    padding: '12px 14px',
    border: '1px solid #111827',
    background: '#111827',
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 800,
    cursor: 'pointer',
    boxSizing: 'border-box',
    width: '100%',
  },
  logoutSidebarBtn: {
    borderRadius: 14,
    padding: '12px 14px',
    border: '1px solid #d1d5db',
    background: '#ffffff',
    color: '#374151',
    fontSize: 14,
    fontWeight: 800,
    cursor: 'pointer',
    boxSizing: 'border-box',
    width: '100%',
  },
  managerBtn: {
    borderRadius: 14,
    padding: '12px 14px',
    border: '1px solid #2563eb',
    background: '#2563eb',
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 800,
    cursor: 'pointer',
    boxSizing: 'border-box',
    width: '100%',
  },
  userCard: {
    borderRadius: 16,
    border: '1px solid #e7edf5',
    background: '#f8fafc',
    padding: 14,
    display: 'grid',
    gap: 4,
    boxSizing: 'border-box',
    minWidth: 0,
  },
  userName: {
    fontSize: 15,
    fontWeight: 800,
    color: '#111827',
    wordBreak: 'break-word',
  },
  userRole: {
    fontSize: 12,
    fontWeight: 800,
    color: '#2563eb',
  },
  userEmail: {
    fontSize: 12,
    color: '#64748b',
    wordBreak: 'break-word',
  },
  sidebarCount: {
    fontSize: 11,
    fontWeight: 800,
    padding: '4px 8px',
    borderRadius: 999,
    background: '#f3f4f6',
    color: '#374151',
    whiteSpace: 'nowrap',
    boxSizing: 'border-box',
  },
  sidebarCountActive: {
    fontSize: 11,
    fontWeight: 800,
    padding: '4px 8px',
    borderRadius: 999,
    background: 'rgba(255,255,255,0.14)',
    color: '#ffffff',
    whiteSpace: 'nowrap',
    boxSizing: 'border-box',
  },
  content: {
    flex: 1,
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    padding: 20,
    paddingTop: 76,
    boxSizing: 'border-box',
    overflowX: 'hidden',
  },
  mobileTopBar: {
    position: 'fixed',
    top: 14,
    left: 14,
    right: 14,
    zIndex: 900,
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    pointerEvents: 'none',
  },
  mobileTopBarTitle: {
    fontSize: 15,
    fontWeight: 800,
    color: '#111827',
    minWidth: 0,
    background: 'rgba(255,255,255,0.92)',
    border: '1px solid #e5e7eb',
    borderRadius: 14,
    padding: '10px 14px',
    boxShadow: '0 10px 22px rgba(15,23,42,0.08)',
    pointerEvents: 'auto',
  },
  menuButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    border: '1px solid #dbe3ee',
    background: '#ffffff',
    color: '#111827',
    fontSize: 20,
    fontWeight: 800,
    cursor: 'pointer',
    boxShadow: '0 10px 22px rgba(15,23,42,0.12)',
    boxSizing: 'border-box',
    flexShrink: 0,
    pointerEvents: 'auto',
  },
  mobileOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15,23,42,0.38)',
    zIndex: 1001,
  },
  headerCard: {
    marginBottom: 18,
    padding: 20,
    borderRadius: 24,
    background: 'linear-gradient(135deg, #ffffff 0%, #f8fbff 100%)',
    border: '1px solid #e7edf5',
    boxShadow: '0 16px 34px rgba(15,23,42,0.06)',
    boxSizing: 'border-box',
    width: '100%',
    overflow: 'hidden',
  },
  headerTop: {
    display: 'flex',
    gap: 14,
    alignItems: 'center',
    flexWrap: 'wrap',
    minWidth: 0,
  },
  logoWrap: {
    width: 66,
    height: 66,
    borderRadius: 18,
    background: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #ede9e3',
    boxShadow: '0 8px 18px rgba(15,23,42,0.06)',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  logo: {
    objectFit: 'contain',
  },
  headerTextWrap: {
    minWidth: 0,
    flex: 1,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 1,
    color: '#8b5e34',
    textTransform: 'uppercase',
    marginBottom: 6,
    wordBreak: 'break-word',
  },
  title: {
    margin: 0,
    fontSize: 32,
    lineHeight: 1.08,
    color: '#111827',
    fontWeight: 800,
    wordBreak: 'break-word',
  },
  subtitle: {
    marginTop: 8,
    marginBottom: 0,
    color: '#6b7280',
    fontSize: 14,
    lineHeight: 1.55,
    wordBreak: 'break-word',
  },
  errorBox: {
    marginBottom: 14,
    padding: 12,
    borderRadius: 14,
    border: '1px solid #fecaca',
    background: '#fff1f2',
    color: '#b91c1c',
    fontSize: 14,
    wordBreak: 'break-word',
    boxSizing: 'border-box',
    width: '100%',
  },
  successBox: {
    marginBottom: 14,
    padding: 12,
    borderRadius: 14,
    border: '1px solid #bbf7d0',
    background: '#f0fdf4',
    color: '#15803d',
    fontSize: 14,
    boxSizing: 'border-box',
  },
  summaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: 12,
    marginBottom: 16,
    width: '100%',
    minWidth: 0,
  },
  summaryTitle: {
    fontSize: 13,
    color: '#6b7280',
    fontWeight: 700,
  },
  summaryValue: {
    fontSize: 32,
    fontWeight: 800,
    color: '#111827',
    marginTop: 8,
    wordBreak: 'break-word',
  },
  filterPanel: {
    marginBottom: 16,
    border: '1px solid #e7edf5',
    borderRadius: 22,
    padding: 16,
    background: '#ffffff',
    boxShadow: '0 10px 24px rgba(15,23,42,0.04)',
    boxSizing: 'border-box',
    width: '100%',
    overflow: 'hidden',
  },
  filterHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 14,
    flexWrap: 'wrap',
  },
  filterHeaderText: {
    minWidth: 0,
    flex: 1,
  },
  filterHeaderButtons: {
    display: 'flex',
    gap: 10,
    flexShrink: 0,
  },
  filterPanelTitle: {
    fontSize: 16,
    fontWeight: 800,
    color: '#111827',
    wordBreak: 'break-word',
  },
  filterPanelSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#6b7280',
    fontWeight: 600,
    wordBreak: 'break-word',
  },
  addTaskBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    border: '1px solid #111827',
    background: '#111827',
    color: '#ffffff',
    fontSize: 26,
    lineHeight: 1,
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 12px 22px rgba(17,24,39,0.18)',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  refreshBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    border: '1px solid #d1d5db',
    background: '#ffffff',
    color: '#111827',
    fontSize: 22,
    lineHeight: 1,
    fontWeight: 700,
    cursor: 'pointer',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  filterBlock: {
    marginTop: 14,
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: 800,
    color: '#6b7280',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  pillRow: {
    display: 'flex',
    gap: 8,
    overflowX: 'auto',
    paddingBottom: 4,
    width: '100%',
  },
  dateFilterRow: {
    display: 'grid',
    gap: 8,
    width: '100%',
  },
  dateInput: {
    width: '100%',
    maxWidth: 240,
    borderRadius: 12,
    border: '1px solid #d1d5db',
    background: '#ffffff',
    color: '#111827',
    padding: '12px 14px',
    fontSize: 14,
    fontWeight: 600,
    outline: 'none',
    boxSizing: 'border-box',
  },
  dateHint: {
    fontSize: 12,
    color: '#6b7280',
    fontWeight: 600,
    wordBreak: 'break-word',
  },
  resultBar: {
    marginBottom: 12,
    paddingLeft: 2,
    width: '100%',
    boxSizing: 'border-box',
  },
  resultText: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: 700,
    wordBreak: 'break-word',
  },
  cardList: {
    display: 'grid',
    gap: 14,
    width: '100%',
  },
  taskCard: {
    border: '1px solid #e7edf5',
    borderRadius: 24,
    padding: 18,
    background: '#ffffff',
    boxShadow: '0 14px 28px rgba(15,23,42,0.05)',
    boxSizing: 'border-box',
    width: '100%',
    maxWidth: '100%',
    overflowX: 'hidden',
  },
  taskMainRow: {
    display: 'flex',
    gap: 16,
    alignItems: 'flex-start',
    minWidth: 0,
    width: '100%',
    flexWrap: 'wrap',
  },
  taskMainContent: {
    minWidth: 0,
    flex: 1,
  },
  cardTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  cardTopLeft: {
    minWidth: 0,
    flex: 1,
  },
  taskCodeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
    minWidth: 0,
  },
  taskCode: {
    fontSize: 26,
    fontWeight: 800,
    color: '#111827',
    letterSpacing: -0.4,
    wordBreak: 'break-word',
  },
  roomLine: {
    marginTop: 10,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    color: '#4b5563',
    fontSize: 15,
    minWidth: 0,
  },
  roomText: {
    color: '#64748b',
    fontWeight: 700,
  },
  roomNo: {
    fontWeight: 800,
    color: '#111827',
  },
  dot: {
    color: '#9ca3af',
  },
  taskText: {
    marginTop: 16,
    fontSize: 20,
    lineHeight: 1.4,
    color: '#0f172a',
    fontWeight: 600,
    wordBreak: 'break-word',
  },
  metaGrid: {
    marginTop: 16,
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
    gap: 10,
    width: '100%',
  },
  metaCard: {
    borderRadius: 16,
    border: '1px solid #edf2f7',
    background: '#f8fafc',
    padding: 12,
    minWidth: 0,
    boxSizing: 'border-box',
  },
  metaCardLabel: {
    fontSize: 11,
    fontWeight: 800,
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  metaCardValue: {
    fontSize: 13,
    color: '#334155',
    lineHeight: 1.45,
    wordBreak: 'break-word',
  },
  metaCardValueStrong: {
    fontSize: 13,
    color: '#0f172a',
    lineHeight: 1.45,
    fontWeight: 800,
    wordBreak: 'break-word',
  },
  buttonRow: {
    display: 'flex',
    gap: 10,
    marginTop: 16,
    flexWrap: 'wrap',
  },
  permissionText: {
    marginTop: 10,
    fontSize: 12,
    color: '#b45309',
    fontWeight: 700,
    wordBreak: 'break-word',
  },
  updatingText: {
    marginTop: 10,
    fontSize: 12,
    color: '#64748b',
    fontWeight: 700,
  },
  pastTaskNote: {
    marginTop: 16,
    fontSize: 12,
    color: '#64748b',
    fontWeight: 700,
    padding: '10px 12px',
    borderRadius: 12,
    background: '#f8fafc',
    border: '1px solid #edf2f7',
    boxSizing: 'border-box',
    wordBreak: 'break-word',
  },
  emptyState: {
    marginTop: 20,
    padding: 26,
    borderRadius: 20,
    background: '#ffffff',
    border: '1px solid #e7edf5',
    textAlign: 'center',
    color: '#64748b',
    boxShadow: '0 10px 24px rgba(15,23,42,0.04)',
    fontWeight: 600,
    boxSizing: 'border-box',
    width: '100%',
  },
  thumbWrap: {
    width: 86,
    maxWidth: '100%',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
  },
  thumbButton: {
    width: 86,
    height: 86,
    borderRadius: 18,
    overflow: 'hidden',
    border: '1px solid #e7edf5',
    background: '#f8fafc',
    padding: 0,
    cursor: 'pointer',
    boxShadow: '0 10px 22px rgba(15,23,42,0.08)',
    boxSizing: 'border-box',
  },
  thumbImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  imageCountBadge: {
    fontSize: 11,
    fontWeight: 800,
    color: '#374151',
    background: '#f3f4f6',
    border: '1px solid #e5e7eb',
    borderRadius: 999,
    padding: '4px 8px',
    whiteSpace: 'nowrap',
    boxSizing: 'border-box',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 1100,
    background: 'rgba(0,0,0,0.82)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    boxSizing: 'border-box',
  },
  modalInner: {
    position: 'relative',
    width: '100%',
    maxWidth: 1100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  modalCloseBtn: {
    position: 'absolute',
    top: -8,
    right: 0,
    width: 42,
    height: 42,
    borderRadius: 999,
    border: '1px solid rgba(255,255,255,0.18)',
    background: 'rgba(255,255,255,0.12)',
    color: '#ffffff',
    fontSize: 26,
    lineHeight: 1,
    cursor: 'pointer',
    zIndex: 2,
    boxSizing: 'border-box',
  },
  modalNavLeft: {
    border: '1px solid rgba(255,255,255,0.18)',
    background: 'rgba(255,255,255,0.12)',
    color: '#ffffff',
    width: 48,
    height: 48,
    borderRadius: 999,
    fontSize: 34,
    lineHeight: 1,
    cursor: 'pointer',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  modalNavRight: {
    border: '1px solid rgba(255,255,255,0.18)',
    background: 'rgba(255,255,255,0.12)',
    color: '#ffffff',
    width: 48,
    height: 48,
    borderRadius: 999,
    fontSize: 34,
    lineHeight: 1,
    cursor: 'pointer',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  modalImageWrap: {
    width: '100%',
    maxWidth: 920,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
  },
  modalImage: {
    width: '100%',
    maxHeight: '80vh',
    objectFit: 'contain',
    borderRadius: 18,
    background: '#111827',
  },
  modalFooter: {
    width: '100%',
    display: 'grid',
    gap: 8,
    justifyItems: 'center',
  },
  modalCounter: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 800,
  },
  modalCaption: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 14,
    lineHeight: 1.5,
    textAlign: 'center',
    maxWidth: 780,
    wordBreak: 'break-word',
  },
  createModalOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 1200,
    background: 'rgba(15,23,42,0.55)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    boxSizing: 'border-box',
  },
  createModalCard: {
    width: '100%',
    maxWidth: 640,
    borderRadius: 24,
    background: '#ffffff',
    border: '1px solid #e7edf5',
    boxShadow: '0 24px 48px rgba(15,23,42,0.18)',
    padding: 18,
    display: 'grid',
    gap: 16,
    maxHeight: '90vh',
    overflowY: 'auto',
    boxSizing: 'border-box',
  },
  loginModalCard: {
    width: '100%',
    maxWidth: 520,
    borderRadius: 24,
    background: '#ffffff',
    border: '1px solid #e7edf5',
    boxShadow: '0 24px 48px rgba(15,23,42,0.18)',
    padding: 18,
    display: 'grid',
    gap: 16,
    maxHeight: '90vh',
    overflowY: 'auto',
    boxSizing: 'border-box',
  },
  createModalTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  createModalTitle: {
    fontSize: 22,
    fontWeight: 800,
    color: '#111827',
    wordBreak: 'break-word',
  },
  createModalSubtitle: {
    marginTop: 6,
    fontSize: 13,
    color: '#6b7280',
    fontWeight: 600,
    lineHeight: 1.45,
    wordBreak: 'break-word',
  },
  createModalCloseBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    border: '1px solid #e5e7eb',
    background: '#ffffff',
    color: '#111827',
    fontSize: 24,
    lineHeight: 1,
    cursor: 'pointer',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  createErrorBox: {
    padding: 12,
    borderRadius: 14,
    border: '1px solid #fecaca',
    background: '#fff1f2',
    color: '#b91c1c',
    fontSize: 14,
    boxSizing: 'border-box',
    wordBreak: 'break-word',
  },
  formBlock: {
    display: 'grid',
    gap: 8,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: 800,
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  formInput: {
    width: '100%',
    borderRadius: 14,
    border: '1px solid #d1d5db',
    background: '#ffffff',
    color: '#111827',
    padding: '14px 16px',
    fontSize: 15,
    fontWeight: 600,
    outline: 'none',
    boxSizing: 'border-box',
  },
  formTextarea: {
    width: '100%',
    minHeight: 110,
    borderRadius: 14,
    border: '1px solid #d1d5db',
    background: '#ffffff',
    color: '#111827',
    padding: '14px 16px',
    fontSize: 15,
    fontWeight: 600,
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  createDeptRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
  },
  uploadBox: {
    display: 'grid',
    gap: 4,
    border: '1px dashed #cbd5e1',
    borderRadius: 16,
    padding: 16,
    background: '#f8fafc',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  uploadBoxTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: '#111827',
    wordBreak: 'break-word',
  },
  uploadBoxSub: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: 600,
    wordBreak: 'break-word',
  },
  photoCounterText: {
    fontSize: 13,
    color: '#334155',
    fontWeight: 700,
    wordBreak: 'break-word',
  },
  previewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))',
    gap: 12,
    width: '100%',
  },
  previewCard: {
    borderRadius: 16,
    border: '1px solid #e5e7eb',
    background: '#f8fafc',
    overflow: 'hidden',
    display: 'grid',
    boxSizing: 'border-box',
    minWidth: 0,
  },
  previewThumb: {
    width: '100%',
    height: 110,
    objectFit: 'cover',
    display: 'block',
  },
  previewName: {
    fontSize: 11,
    color: '#334155',
    fontWeight: 700,
    padding: '8px 10px 0 10px',
    wordBreak: 'break-word',
  },
  previewRemoveBtn: {
    margin: 10,
    borderRadius: 10,
    border: '1px solid #fecaca',
    background: '#fff1f2',
    color: '#b91c1c',
    fontSize: 12,
    fontWeight: 800,
    padding: '8px 10px',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  createActionRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    flexWrap: 'wrap',
    marginTop: 4,
  },
  cancelBtn: {
    minWidth: 110,
    borderRadius: 14,
    padding: '12px 16px',
    border: '1px solid #d1d5db',
    background: '#ffffff',
    color: '#374151',
    fontSize: 14,
    fontWeight: 800,
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  submitBtn: {
    minWidth: 130,
    borderRadius: 14,
    padding: '12px 18px',
    border: '1px solid #111827',
    background: '#111827',
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 800,
    cursor: 'pointer',
    boxShadow: '0 12px 22px rgba(17,24,39,0.18)',
    boxSizing: 'border-box',
  },
};
